### ISSUE TITLE
请教下电量显示和触摸板无法使用应该如何进行排查

### ISSUE THREAD

**Issue by Narizgnaw** [mendax1234/ThinkpadX390-Opencore-EFI#10]
您好，我的型号为ThinkPad X390 20Q0 A026CD，安装之后其他项均比较完美，有两个问题请教下大佬应该如何进行排查：
1.config.plist中已启用ACPIBatteryManager.kext，但是电量无法正常显示，表现为：菜单栏不显示电量，设置中显示电量为0%；
2.触控板手势可以使用，但是设置中显示无触控板，点击触控板选项，显示找不到触控板，无法进行单指轻点操作及设置触控板相关选项。
系统：macOS Big Sur 11.5.2
感谢大佬开发相关内容。

**Comment by mendax1234** [comment]
> 1.config.plist中已启用ACPIBatteryManager.kext，但是电量无法正常显示，表现为：菜单栏不显示电量，设置中显示电量为0%；
你的dsdt.aml有没有换成自己的，如果没有的话，请从自己的主板提取dsdt.aml并改错，添加电池补丁（如果你改好错了，但是不会添加电池补丁，可以把dsdt.aml发给我，我帮你加）。然后，用改好的dsdt.aml替换原来EFI/OC/ACPI 下的dsdt.aml. 。

> 2.触控板手势可以使用，但是设置中显示无触控板，点击触控板选项，显示找不到触控板，无法进行单指轻点操作及设置触控板相关选项。
这个的话你更新一下acidanthera的最新voodooPS2驱动试试，可能是你触摸板型号比较新，
这边我放个链接：
[VoodooPS2](https://github.com/acidanthera/VoodooPS2)

<font size = 7>**如果还有什么问题的话，随时提出😀**</font>
