### ISSUE TITLE
My NVMe is being recognized as an external drive

### ISSUE THREAD

**Issue by jkashuba07** [mendax1234/ThinkpadX390-Opencore-EFI#11]
As title says when I am in macOS Recovery to install Big Sur, it won't let me. If I format it Mac Extended Journled then when I go to install I get an error that says it can't be installed onto it because it has no firmware partition. If I format APFS, I can attempt to install but fails halfway through.

Any suggestions? 

I created the install media. Mounted the EFI partition, then copied the EFI folder of the release from this repo to it.

Thanks.

**Comment by mendax1234** [comment]
Try deleting the dsdt.aml and the NVMeFix.kext . 

For installing problem , l recommend that you should format it to APFS , l guess that you have this problem because you NVME disk is recognized as an external one. 

Besides, what is you type of NVME? This really counts too. Because there do exist some SSD that Hacintosh can't be installed on. Like Samsung's PM981 and PM981a.

**Comment by jkashuba07** [comment]
Thanks for the reply. Unfortunately that did not work.  I have a Toshiba NVMe 256GB.

That being said, I found a similar project here on Github, and I tried his configuration, and it worked great. I am a novice when it comes to config and compare. The one difference I noticed is he may have been using a new version of Open-Core. But I doubt that was the issue.

**Comment by jkashuba07** [comment]
If you would like, I can test it for you, for your information, and I will post back exact model of my Toshiba NVME.

**Comment by deli-lover** [comment]
> Thanks for the reply. Unfortunately that did not work. I have a Toshiba NVMe 256GB.
> 
> That being said, I found a similar project here on Github, and I tried his configuration, and it worked great. I am a novice when it comes to config and compare. The one difference I noticed is he may have been using a new version of Open-Core. But I doubt that was the issue.

Can you link me this? I am having the same problem.

**Comment by jkashuba07** [comment]
> 

Hi, sorry for late reply. I believe it was this one I was able to get my Yoga X390 working with Big Sur

https://github.com/Chitpixel/X390-OC-EFI
