### ISSUE TITLE
Does this repo support ThinkPad X395?

### ISSUE THREAD

**Issue by JobberRT** [mendax1234/ThinkpadX390-Opencore-EFI#18]
Hi, thanks for making this amazing project.

ThinkPad `X390` and `X395` are bascially the same model except `X395` has AMD Ryzen CPU rather than Intel Core CPU, so I wonder if this project support `X395` as well. But I know different CPU platform will lead to different motherboard and different BIOS, so I won't give too much hope to it ^_^

**Comment by mendax1234** [comment]
I haven't tried it 😂 But as far as l am concerned, l think it is impossible to use this EFI directly on your X395. And l am also uncertain about whether someone has successfully installed hackintosh on a platform with AMD Ryzen CPU.

**Comment by dustojnikhummer** [comment]
> I haven't tried it 😂 But as far as l am concerned, l think it is impossible to use this EFI directly on your X395. And l am also uncertain about whether someone has successfully installed hackintosh on a platform with AMD Ryzen CPU.

Curious about X390 Yoga. Might give that a shot myself at some point. I guess the touch won't work properly, unless faked with some wacom driver or something.

**Comment by lioneliio** [comment]
Amd mobile platform (ThinkPad X395) is not surpported by OpenCore.
[https://dortania.github.io/OpenCore-Install-Guide/macos-limits.html#gpu-support](url)
