### ISSUE TITLE
20Q0系列的x390无法正常使用

### ISSUE THREAD

**Issue by m0regithub** [mendax1234/ThinkpadX390-Opencore-EFI#5]
thinkpad x390 20Q0系列主板使用该引导，需要删除DSDT.aml文件
提醒相应主板型号用户一下

**Comment by mendax1234** [comment]
确实，毕竟每个人的主板都不一样，dsdt可能会用不了，需要更换自己的修改过后的dsdt才能正常使用。

**Comment by m0regithub** [comment]
我看了下，您的主板型号和我的主板型号相同，是不是bios设置的有问题
直接使用您的opencore无法使用10.15.7，删除dtst.aml后可以进入但是电量也无法显示

**Comment by m0regithub** [comment]
对了您的bios版本号是什么

**Comment by mendax1234** [comment]
bios版本不重要，还有dsdt要用你自己改好错加好补丁的才行

**Comment by m0regithub** [comment]
我的dsdt做好了，到时候可以补充上传一下

**Comment by mendax1234** [comment]
好的
