### ISSUE TITLE
Install instructions

### ISSUE THREAD

**Issue by mataslauzadis** [mendax1234/ThinkpadX390-Opencore-EFI#7]
Hi, thanks for making this available.

Are there any instructions? Do I just take your EFI folder and use it? Do I still have to modify config.plist following OpenCore instructions?

**Comment by mendax1234** [comment]
You just need to use my EFI folder. You don't have to replace the config.plist. After you've done this,reboot your computer to see whether you can enter the hackintosh. If not,try to delete the dsdt.aml in the EFI/OC/ACPI and delete it from the config.plist. If you have other questions, just feel free to ask! Wish you a happy hackintosh journey!

**Comment by mataslauzadis** [comment]
Thanks!
