### ISSUE TITLE
你好，我想请问一下这个EFI对睡眠支持到什么样的程度

### ISSUE THREAD

**Issue by xuyihan-china** [mendax1234/ThinkpadX390-Opencore-EFI#9]

**Comment by mendax1234** [comment]
睡眠应该挺完美的

发送自 Windows 10 版邮件应用

发件人: ManuXu
发送时间: 2021年7月15日 16:08
收件人: mendax1234/ThinkpadX390-Opencore-EFI
抄送: Subscribed
主题: [mendax1234/ThinkpadX390-Opencore-EFI] 你好，我想请问一下这个EFI对睡眠支持到什么样的程度 (#9)

**Comment by xuyihan-china** [comment]
thanks
